all:
	taurusuic4 ui/LoopsPlots.ui -o ui_LoopsPlots.py
	taurusuic4 ui/DiagPlots.ui -o ui_DiagPlots.py
	taurusuic4 ui/TimaAndDecimation.ui -o ui_TimaAndDecimation.py
	taurusuic4 ui/MainView.ui -o ui_MainView.py
	taurusuic4 ui/FileLoader.ui -o ui_FileLoader.py
