# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgets/ui/FacadeAdjustments.ui'
#
# Created: Mon Jul 28 15:01:17 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_facadeAdjustments(object):
    def setupUi(self, facadeAdjustments):
        facadeAdjustments.setObjectName(_fromUtf8("facadeAdjustments"))
        facadeAdjustments.resize(343, 397)
        self.gridLayout_4 = QtGui.QGridLayout(facadeAdjustments)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.scrollArea = QtGui.QScrollArea(facadeAdjustments)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 329, 383))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.buttonBox = QtGui.QDialogButtonBox(self.scrollAreaWidgetContents)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 1)
        self.PDIsCav = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.PDIsCav.setObjectName(_fromUtf8("PDIsCav"))
        self.gridLayout_5 = QtGui.QGridLayout(self.PDIsCav)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.PDIsCavOLabel = QtGui.QLabel(self.PDIsCav)
        self.PDIsCavOLabel.setObjectName(_fromUtf8("PDIsCavOLabel"))
        self.gridLayout_5.addWidget(self.PDIsCavOLabel, 1, 4, 1, 1)
        spacerItem = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 1, 6, 1, 1)
        self.PDIsCavCLabel = QtGui.QLabel(self.PDIsCav)
        self.PDIsCavCLabel.setObjectName(_fromUtf8("PDIsCavCLabel"))
        self.gridLayout_5.addWidget(self.PDIsCavCLabel, 1, 1, 1, 1)
        self.PDIsCavCValue = QtGui.QDoubleSpinBox(self.PDIsCav)
        self.PDIsCavCValue.setDecimals(4)
        self.PDIsCavCValue.setSingleStep(0.0001)
        self.PDIsCavCValue.setObjectName(_fromUtf8("PDIsCavCValue"))
        self.gridLayout_5.addWidget(self.PDIsCavCValue, 1, 2, 1, 1)
        self.PDIsCavOValue = QtGui.QDoubleSpinBox(self.PDIsCav)
        self.PDIsCavOValue.setDecimals(4)
        self.PDIsCavOValue.setSingleStep(0.0001)
        self.PDIsCavOValue.setObjectName(_fromUtf8("PDIsCavOValue"))
        self.gridLayout_5.addWidget(self.PDIsCavOValue, 1, 5, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(22, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 1, 3, 1, 1)
        self.PDIsCavFormula = QtGui.QLabel(self.PDIsCav)
        self.PDIsCavFormula.setAlignment(QtCore.Qt.AlignCenter)
        self.PDIsCavFormula.setObjectName(_fromUtf8("PDIsCavFormula"))
        self.gridLayout_5.addWidget(self.PDIsCavFormula, 0, 1, 1, 5)
        self.gridLayout.addWidget(self.PDIsCav, 1, 0, 1, 1)
        self.FwCav = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.FwCav.setObjectName(_fromUtf8("FwCav"))
        self.gridLayout_6 = QtGui.QGridLayout(self.FwCav)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.FwCavOLabel = QtGui.QLabel(self.FwCav)
        self.FwCavOLabel.setObjectName(_fromUtf8("FwCavOLabel"))
        self.gridLayout_6.addWidget(self.FwCavOLabel, 1, 4, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 1, 0, 1, 1)
        self.FwCavCLabel = QtGui.QLabel(self.FwCav)
        self.FwCavCLabel.setObjectName(_fromUtf8("FwCavCLabel"))
        self.gridLayout_6.addWidget(self.FwCavCLabel, 1, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 1, 6, 1, 1)
        self.FwCavOValue = QtGui.QDoubleSpinBox(self.FwCav)
        self.FwCavOValue.setDecimals(4)
        self.FwCavOValue.setSingleStep(0.0001)
        self.FwCavOValue.setObjectName(_fromUtf8("FwCavOValue"))
        self.gridLayout_6.addWidget(self.FwCavOValue, 1, 5, 1, 1)
        self.FwCavCValue = QtGui.QDoubleSpinBox(self.FwCav)
        self.FwCavCValue.setDecimals(4)
        self.FwCavCValue.setSingleStep(0.0001)
        self.FwCavCValue.setObjectName(_fromUtf8("FwCavCValue"))
        self.gridLayout_6.addWidget(self.FwCavCValue, 1, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(22, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem5, 1, 3, 1, 1)
        self.FwCavFormula = QtGui.QLabel(self.FwCav)
        self.FwCavFormula.setAlignment(QtCore.Qt.AlignCenter)
        self.FwCavFormula.setObjectName(_fromUtf8("FwCavFormula"))
        self.gridLayout_6.addWidget(self.FwCavFormula, 0, 1, 1, 5)
        self.gridLayout.addWidget(self.FwCav, 2, 0, 1, 1)
        self.cavityVolts = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.cavityVolts.setObjectName(_fromUtf8("cavityVolts"))
        self.gridLayout_2 = QtGui.QGridLayout(self.cavityVolts)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 1, 6, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 1, 3, 1, 1)
        self.cavityVoltsMValue = QtGui.QDoubleSpinBox(self.cavityVolts)
        self.cavityVoltsMValue.setDecimals(4)
        self.cavityVoltsMValue.setSingleStep(0.0001)
        self.cavityVoltsMValue.setObjectName(_fromUtf8("cavityVoltsMValue"))
        self.gridLayout_2.addWidget(self.cavityVoltsMValue, 1, 2, 1, 1)
        self.cavityVoltsNValue = QtGui.QDoubleSpinBox(self.cavityVolts)
        self.cavityVoltsNValue.setDecimals(4)
        self.cavityVoltsNValue.setSingleStep(0.0001)
        self.cavityVoltsNValue.setObjectName(_fromUtf8("cavityVoltsNValue"))
        self.gridLayout_2.addWidget(self.cavityVoltsNValue, 1, 5, 1, 1)
        self.cavityVoltsNLabel = QtGui.QLabel(self.cavityVolts)
        self.cavityVoltsNLabel.setObjectName(_fromUtf8("cavityVoltsNLabel"))
        self.gridLayout_2.addWidget(self.cavityVoltsNLabel, 1, 4, 1, 1)
        self.cavityVoltsMLabel = QtGui.QLabel(self.cavityVolts)
        self.cavityVoltsMLabel.setObjectName(_fromUtf8("cavityVoltsMLabel"))
        self.gridLayout_2.addWidget(self.cavityVoltsMLabel, 1, 1, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 1, 0, 1, 1)
        self.cavityVoltsFormula = QtGui.QLabel(self.cavityVolts)
        self.cavityVoltsFormula.setAlignment(QtCore.Qt.AlignCenter)
        self.cavityVoltsFormula.setObjectName(_fromUtf8("cavityVoltsFormula"))
        self.gridLayout_2.addWidget(self.cavityVoltsFormula, 0, 1, 1, 5)
        self.gridLayout.addWidget(self.cavityVolts, 0, 0, 1, 1)
        self.RvCav = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.RvCav.setObjectName(_fromUtf8("RvCav"))
        self.gridLayout_7 = QtGui.QGridLayout(self.RvCav)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        spacerItem9 = QtGui.QSpacerItem(22, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem9, 1, 3, 1, 1)
        self.RvCavCLabel = QtGui.QLabel(self.RvCav)
        self.RvCavCLabel.setObjectName(_fromUtf8("RvCavCLabel"))
        self.gridLayout_7.addWidget(self.RvCavCLabel, 1, 1, 1, 1)
        self.RvCavCValue = QtGui.QDoubleSpinBox(self.RvCav)
        self.RvCavCValue.setDecimals(4)
        self.RvCavCValue.setSingleStep(0.0001)
        self.RvCavCValue.setObjectName(_fromUtf8("RvCavCValue"))
        self.gridLayout_7.addWidget(self.RvCavCValue, 1, 2, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem10, 1, 0, 1, 1)
        self.RvCavOLabel = QtGui.QLabel(self.RvCav)
        self.RvCavOLabel.setObjectName(_fromUtf8("RvCavOLabel"))
        self.gridLayout_7.addWidget(self.RvCavOLabel, 1, 4, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem11, 1, 6, 1, 1)
        self.RvCavOValue = QtGui.QDoubleSpinBox(self.RvCav)
        self.RvCavOValue.setDecimals(4)
        self.RvCavOValue.setSingleStep(0.0001)
        self.RvCavOValue.setObjectName(_fromUtf8("RvCavOValue"))
        self.gridLayout_7.addWidget(self.RvCavOValue, 1, 5, 1, 1)
        self.RvCavFormula = QtGui.QLabel(self.RvCav)
        self.RvCavFormula.setAlignment(QtCore.Qt.AlignCenter)
        self.RvCavFormula.setObjectName(_fromUtf8("RvCavFormula"))
        self.gridLayout_7.addWidget(self.RvCavFormula, 0, 1, 1, 5)
        self.gridLayout.addWidget(self.RvCav, 3, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(facadeAdjustments)
        QtCore.QMetaObject.connectSlotsByName(facadeAdjustments)
        facadeAdjustments.setTabOrder(self.cavityVoltsMValue, self.cavityVoltsNValue)
        facadeAdjustments.setTabOrder(self.cavityVoltsNValue, self.buttonBox)

    def retranslateUi(self, facadeAdjustments):
        facadeAdjustments.setWindowTitle(QtGui.QApplication.translate("facadeAdjustments", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.PDIsCav.setTitle(QtGui.QApplication.translate("facadeAdjustments", "PDisCav", None, QtGui.QApplication.UnicodeUTF8))
        self.PDIsCavOLabel.setText(QtGui.QApplication.translate("facadeAdjustments", "offset", None, QtGui.QApplication.UnicodeUTF8))
        self.PDIsCavCLabel.setText(QtGui.QApplication.translate("facadeAdjustments", "couple", None, QtGui.QApplication.UnicodeUTF8))
        self.PDIsCavFormula.setText(QtGui.QApplication.translate("facadeAdjustments", "y = x^2/10e8/10^c-o", None, QtGui.QApplication.UnicodeUTF8))
        self.FwCav.setTitle(QtGui.QApplication.translate("facadeAdjustments", "FwCav", None, QtGui.QApplication.UnicodeUTF8))
        self.FwCavOLabel.setText(QtGui.QApplication.translate("facadeAdjustments", "offset", None, QtGui.QApplication.UnicodeUTF8))
        self.FwCavCLabel.setText(QtGui.QApplication.translate("facadeAdjustments", "couple", None, QtGui.QApplication.UnicodeUTF8))
        self.FwCavFormula.setText(QtGui.QApplication.translate("facadeAdjustments", "y = x^2/10e8/10^c-o", None, QtGui.QApplication.UnicodeUTF8))
        self.cavityVolts.setTitle(QtGui.QApplication.translate("facadeAdjustments", "Cavity Volts", None, QtGui.QApplication.UnicodeUTF8))
        self.cavityVoltsNLabel.setText(QtGui.QApplication.translate("facadeAdjustments", "offset", None, QtGui.QApplication.UnicodeUTF8))
        self.cavityVoltsMLabel.setText(QtGui.QApplication.translate("facadeAdjustments", "slope", None, QtGui.QApplication.UnicodeUTF8))
        self.cavityVoltsFormula.setText(QtGui.QApplication.translate("facadeAdjustments", "y = (x-n)/m", None, QtGui.QApplication.UnicodeUTF8))
        self.RvCav.setTitle(QtGui.QApplication.translate("facadeAdjustments", "RwCav", None, QtGui.QApplication.UnicodeUTF8))
        self.RvCavCLabel.setText(QtGui.QApplication.translate("facadeAdjustments", "couple", None, QtGui.QApplication.UnicodeUTF8))
        self.RvCavOLabel.setText(QtGui.QApplication.translate("facadeAdjustments", "offset", None, QtGui.QApplication.UnicodeUTF8))
        self.RvCavFormula.setText(QtGui.QApplication.translate("facadeAdjustments", "y = x^2/10e8/10^c-o", None, QtGui.QApplication.UnicodeUTF8))

from taurus.qt.qtgui.panel import TaurusWidget
