# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgets/ui/FacadeAdjustments.ui'
#
# Created: Thu Dec 11 16:12:38 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_facadeAdjustments(object):
    def setupUi(self, facadeAdjustments):
        facadeAdjustments.setObjectName(_fromUtf8("facadeAdjustments"))
        facadeAdjustments.resize(392, 450)
        self.gridLayout_4 = QtGui.QGridLayout(facadeAdjustments)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.scrollArea = QtGui.QScrollArea(facadeAdjustments)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 378, 436))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 2, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(self.scrollAreaWidgetContents)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.Reset)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 6, 1, 1, 1)
        self.cavityVolts_kV = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.cavityVolts_kV.setObjectName(_fromUtf8("cavityVolts_kV"))
        self.gridLayout_5 = QtGui.QGridLayout(self.cavityVolts_kV)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.cavityVolts_kV_NLabel = QtGui.QLabel(self.cavityVolts_kV)
        self.cavityVolts_kV_NLabel.setObjectName(_fromUtf8("cavityVolts_kV_NLabel"))
        self.gridLayout_5.addWidget(self.cavityVolts_kV_NLabel, 1, 4, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 1, 6, 1, 1)
        self.cavityVolts_kV_MLabel = QtGui.QLabel(self.cavityVolts_kV)
        self.cavityVolts_kV_MLabel.setObjectName(_fromUtf8("cavityVolts_kV_MLabel"))
        self.gridLayout_5.addWidget(self.cavityVolts_kV_MLabel, 1, 1, 1, 1)
        self.cavityVolts_kV_MValue = QtGui.QDoubleSpinBox(self.cavityVolts_kV)
        self.cavityVolts_kV_MValue.setDecimals(4)
        self.cavityVolts_kV_MValue.setSingleStep(0.0001)
        self.cavityVolts_kV_MValue.setObjectName(_fromUtf8("cavityVolts_kV_MValue"))
        self.gridLayout_5.addWidget(self.cavityVolts_kV_MValue, 1, 2, 1, 1)
        self.cavityVolts_kV_NValue = QtGui.QDoubleSpinBox(self.cavityVolts_kV)
        self.cavityVolts_kV_NValue.setDecimals(4)
        self.cavityVolts_kV_NValue.setSingleStep(0.0001)
        self.cavityVolts_kV_NValue.setObjectName(_fromUtf8("cavityVolts_kV_NValue"))
        self.gridLayout_5.addWidget(self.cavityVolts_kV_NValue, 1, 5, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 1, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(22, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 1, 3, 1, 1)
        self.cavityVolts_kV_Formula = QtGui.QLineEdit(self.cavityVolts_kV)
        self.cavityVolts_kV_Formula.setAlignment(QtCore.Qt.AlignCenter)
        self.cavityVolts_kV_Formula.setObjectName(_fromUtf8("cavityVolts_kV_Formula"))
        self.gridLayout_5.addWidget(self.cavityVolts_kV_Formula, 0, 1, 1, 5)
        self.gridLayout.addWidget(self.cavityVolts_kV, 1, 1, 1, 1)
        self.FwCav = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.FwCav.setObjectName(_fromUtf8("FwCav"))
        self.gridLayout_6 = QtGui.QGridLayout(self.FwCav)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.FwCavOLabel = QtGui.QLabel(self.FwCav)
        self.FwCavOLabel.setObjectName(_fromUtf8("FwCavOLabel"))
        self.gridLayout_6.addWidget(self.FwCavOLabel, 1, 4, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem6, 1, 0, 1, 1)
        self.FwCavCLabel = QtGui.QLabel(self.FwCav)
        self.FwCavCLabel.setObjectName(_fromUtf8("FwCavCLabel"))
        self.gridLayout_6.addWidget(self.FwCavCLabel, 1, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem7, 1, 6, 1, 1)
        self.FwCavOValue = QtGui.QDoubleSpinBox(self.FwCav)
        self.FwCavOValue.setDecimals(4)
        self.FwCavOValue.setSingleStep(0.0001)
        self.FwCavOValue.setObjectName(_fromUtf8("FwCavOValue"))
        self.gridLayout_6.addWidget(self.FwCavOValue, 1, 5, 1, 1)
        self.FwCavCValue = QtGui.QDoubleSpinBox(self.FwCav)
        self.FwCavCValue.setDecimals(4)
        self.FwCavCValue.setSingleStep(0.0001)
        self.FwCavCValue.setObjectName(_fromUtf8("FwCavCValue"))
        self.gridLayout_6.addWidget(self.FwCavCValue, 1, 2, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(22, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem8, 1, 3, 1, 1)
        self.FwCavFormula = QtGui.QLineEdit(self.FwCav)
        self.FwCavFormula.setAlignment(QtCore.Qt.AlignCenter)
        self.FwCavFormula.setObjectName(_fromUtf8("FwCavFormula"))
        self.gridLayout_6.addWidget(self.FwCavFormula, 0, 1, 1, 5)
        self.gridLayout.addWidget(self.FwCav, 2, 1, 1, 1)
        self.RvCav = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.RvCav.setObjectName(_fromUtf8("RvCav"))
        self.gridLayout_7 = QtGui.QGridLayout(self.RvCav)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        spacerItem9 = QtGui.QSpacerItem(22, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem9, 1, 3, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem10, 1, 6, 1, 1)
        self.RvCavCLabel = QtGui.QLabel(self.RvCav)
        self.RvCavCLabel.setObjectName(_fromUtf8("RvCavCLabel"))
        self.gridLayout_7.addWidget(self.RvCavCLabel, 1, 1, 1, 1)
        self.RvCavCValue = QtGui.QDoubleSpinBox(self.RvCav)
        self.RvCavCValue.setDecimals(4)
        self.RvCavCValue.setSingleStep(0.0001)
        self.RvCavCValue.setObjectName(_fromUtf8("RvCavCValue"))
        self.gridLayout_7.addWidget(self.RvCavCValue, 1, 2, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem11, 1, 0, 1, 1)
        self.RvCavOLabel = QtGui.QLabel(self.RvCav)
        self.RvCavOLabel.setObjectName(_fromUtf8("RvCavOLabel"))
        self.gridLayout_7.addWidget(self.RvCavOLabel, 1, 4, 1, 1)
        self.RvCavOValue = QtGui.QDoubleSpinBox(self.RvCav)
        self.RvCavOValue.setDecimals(4)
        self.RvCavOValue.setSingleStep(0.0001)
        self.RvCavOValue.setObjectName(_fromUtf8("RvCavOValue"))
        self.gridLayout_7.addWidget(self.RvCavOValue, 1, 5, 1, 1)
        self.RvCavFormula = QtGui.QLineEdit(self.RvCav)
        self.RvCavFormula.setAlignment(QtCore.Qt.AlignCenter)
        self.RvCavFormula.setObjectName(_fromUtf8("RvCavFormula"))
        self.gridLayout_7.addWidget(self.RvCavFormula, 0, 1, 1, 5)
        self.gridLayout.addWidget(self.RvCav, 3, 1, 1, 1)
        self.FwLoad = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.FwLoad.setObjectName(_fromUtf8("FwLoad"))
        self.gridLayout_8 = QtGui.QGridLayout(self.FwLoad)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        spacerItem12 = QtGui.QSpacerItem(22, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem12, 1, 3, 1, 1)
        self.FwLoadCLabel = QtGui.QLabel(self.FwLoad)
        self.FwLoadCLabel.setObjectName(_fromUtf8("FwLoadCLabel"))
        self.gridLayout_8.addWidget(self.FwLoadCLabel, 1, 1, 1, 1)
        self.FwLoadCValue = QtGui.QDoubleSpinBox(self.FwLoad)
        self.FwLoadCValue.setDecimals(4)
        self.FwLoadCValue.setSingleStep(0.0001)
        self.FwLoadCValue.setObjectName(_fromUtf8("FwLoadCValue"))
        self.gridLayout_8.addWidget(self.FwLoadCValue, 1, 2, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem13, 1, 0, 1, 1)
        self.FwLoadOLabel = QtGui.QLabel(self.FwLoad)
        self.FwLoadOLabel.setObjectName(_fromUtf8("FwLoadOLabel"))
        self.gridLayout_8.addWidget(self.FwLoadOLabel, 1, 4, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem14, 1, 6, 1, 1)
        self.FwLoadOValue = QtGui.QDoubleSpinBox(self.FwLoad)
        self.FwLoadOValue.setDecimals(4)
        self.FwLoadOValue.setSingleStep(0.0001)
        self.FwLoadOValue.setObjectName(_fromUtf8("FwLoadOValue"))
        self.gridLayout_8.addWidget(self.FwLoadOValue, 1, 5, 1, 1)
        self.FwLoadFormula = QtGui.QLineEdit(self.FwLoad)
        self.FwLoadFormula.setAlignment(QtCore.Qt.AlignCenter)
        self.FwLoadFormula.setObjectName(_fromUtf8("FwLoadFormula"))
        self.gridLayout_8.addWidget(self.FwLoadFormula, 0, 1, 1, 5)
        self.gridLayout.addWidget(self.FwLoad, 4, 1, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem15, 0, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(facadeAdjustments)
        QtCore.QMetaObject.connectSlotsByName(facadeAdjustments)
        facadeAdjustments.setTabOrder(self.cavityVolts_kV_MValue, self.cavityVolts_kV_NValue)
        facadeAdjustments.setTabOrder(self.cavityVolts_kV_NValue, self.FwCavCValue)
        facadeAdjustments.setTabOrder(self.FwCavCValue, self.FwCavOValue)
        facadeAdjustments.setTabOrder(self.FwCavOValue, self.RvCavCValue)
        facadeAdjustments.setTabOrder(self.RvCavCValue, self.RvCavOValue)
        facadeAdjustments.setTabOrder(self.RvCavOValue, self.FwLoadCValue)
        facadeAdjustments.setTabOrder(self.FwLoadCValue, self.FwLoadOValue)
        facadeAdjustments.setTabOrder(self.FwLoadOValue, self.buttonBox)
        facadeAdjustments.setTabOrder(self.buttonBox, self.scrollArea)

    def retranslateUi(self, facadeAdjustments):
        facadeAdjustments.setWindowTitle(QtGui.QApplication.translate("facadeAdjustments", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.cavityVolts_kV.setTitle(QtGui.QApplication.translate("facadeAdjustments", "CavVolt_kV [x = CavVolt]", None, QtGui.QApplication.UnicodeUTF8))
        self.cavityVolts_kV_NLabel.setText(QtGui.QApplication.translate("facadeAdjustments", "offset", None, QtGui.QApplication.UnicodeUTF8))
        self.cavityVolts_kV_MLabel.setText(QtGui.QApplication.translate("facadeAdjustments", "slope", None, QtGui.QApplication.UnicodeUTF8))
        self.cavityVolts_kV_Formula.setText(QtGui.QApplication.translate("facadeAdjustments", "y = x*m-n", None, QtGui.QApplication.UnicodeUTF8))
        self.FwCav.setTitle(QtGui.QApplication.translate("facadeAdjustments", "FwCav_kW [x = FwCav]", None, QtGui.QApplication.UnicodeUTF8))
        self.FwCavOLabel.setText(QtGui.QApplication.translate("facadeAdjustments", "offset", None, QtGui.QApplication.UnicodeUTF8))
        self.FwCavCLabel.setText(QtGui.QApplication.translate("facadeAdjustments", "couple", None, QtGui.QApplication.UnicodeUTF8))
        self.FwCavFormula.setText(QtGui.QApplication.translate("facadeAdjustments", "y = x^2/1e5/10^c+o", None, QtGui.QApplication.UnicodeUTF8))
        self.RvCav.setTitle(QtGui.QApplication.translate("facadeAdjustments", "RwCav_kW [x = RwCav]", None, QtGui.QApplication.UnicodeUTF8))
        self.RvCavCLabel.setText(QtGui.QApplication.translate("facadeAdjustments", "couple", None, QtGui.QApplication.UnicodeUTF8))
        self.RvCavOLabel.setText(QtGui.QApplication.translate("facadeAdjustments", "offset", None, QtGui.QApplication.UnicodeUTF8))
        self.RvCavFormula.setText(QtGui.QApplication.translate("facadeAdjustments", "y = x^2/1e8/10^c+o", None, QtGui.QApplication.UnicodeUTF8))
        self.FwLoad.setTitle(QtGui.QApplication.translate("facadeAdjustments", "FwLoad_kW [x = FwLoad]", None, QtGui.QApplication.UnicodeUTF8))
        self.FwLoadCLabel.setText(QtGui.QApplication.translate("facadeAdjustments", "couple", None, QtGui.QApplication.UnicodeUTF8))
        self.FwLoadOLabel.setText(QtGui.QApplication.translate("facadeAdjustments", "offset", None, QtGui.QApplication.UnicodeUTF8))
        self.FwLoadFormula.setText(QtGui.QApplication.translate("facadeAdjustments", "y = x^2/1e8/10^c+o", None, QtGui.QApplication.UnicodeUTF8))

from taurus.qt.qtgui.panel import TaurusWidget
